language: java
cache:
  directories:
    - $HOME/.gradle
jdk:
  - openjdk12
  - openjdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
script:
  - ./gradlew check
#  - ./gradlew codeCoverageReport
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
